# .streamlit/secrets.toml
DATABRICKS_SERVER_HOSTNAME = "dbc-8143f87b-1afc.cloud.databricks.com"
DATABRICKS_HTTP_PATH = "/sql/1.0/warehouses/1cb2f41fc550f7ff"
DATABRICKS_ACCESS_TOKEN = "dapi6215ec30dbc2f0f70fb793f680aea159"
