# .streamlit/secrets.toml
[databricks]
server_hostname = "dbc-8143f87b-1afc.cloud.databricks.com"
http_path = "/sql/1.0/warehouses/1cb2f41fc550f7ff"
access_token = "dapi6215ec30dbc2f0f70fb793f680aea159"
